# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# NOTICE: This file has been modified by Intel Corporation.
# Original file can be found at https://github.com/tinkerbell/charts.

apiVersion: v2
name: tinkerbell_tink
description: A Helm chart for tinkerbell_tink

type: application

version: 1.6.0

appVersion: "1.4.0"
