# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pxe-server-config
data:
  dnsmasq.conf: |
    interface={{ required "config.interface is mandatory!" .Values.config.interface }}
    bind-interfaces
    port=0
    # subnetAddress is a network address of an IP subnet that is used to match
    # incoming DHCP requests. Only DHCP requests coming from hosts in the subnet will be handled.
    # The line below is used to turn dnsmasq into ProxyDHCP mode. 
    {{- if .Values.config.proxydhcp }}
    dhcp-range={{ required "config.subnetAddress is mandatory!" .Values.config.subnetAddress }},proxy
    dhcp-match=set:pxe,60,PXEClient
    dhcp-match=set:efi64,option:client-arch,7
    pxe-service=tag:pxe,tag:efi64,x86-64_EFI,"Network Boot UEFI x86_64",ipxe.efi,{{ required "config.bootServerIP is mandatory!" .Values.config.bootServerIP }}
    {{- else }}
    dhcp-range=
    {{- end }}
    user=nobody
    group=nobody
    
    pid-file=/var/run/eim-dnsmasq/dnsmasq.pid
    leasefile-ro
    no-ping
    no-hosts
    no-resolv

    enable-tftp
    tftp-root=/var/lib/tftp
    tftp-secure
    tftp-no-blocksize
    tftp-port-range={{ .Values.config.tftp.portRangeStart }},{{ .Values.config.tftp.portRangeEnd }}
    {{- if .Values.config.debug }}
    log-dhcp
    log-queries
    log-facility=-
    log-debug
    {{- end }}
