# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loca-templates-manager.fullname" . }}-config
type: Opaque
stringData:
  config: |
{{- .Values.config | toJson | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loca-templates-manager.fullname" . }}
type: Opaque
stringData:
{{- range $index, $value := .Values.providerConfig }}
  loca-ca{{ $index }}.crt: {{ $value.loca_ca_cert | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loca-templates-manager.fullname" . }}-certificates
type: Opaque
stringData:
{{- range $index, $value := .Values.ubuntu_repos_certificates }}
  ubuntu-ca{{ $index }}.crt: {{ $value | quote }}
{{- end }}
