# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loca-templates-manager.fullname" . }}
  labels:
    {{- include "loca-templates-manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "loca-templates-manager.selectorLabels" . | nindent 4 }}
{{- end }}
