# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: exporter
description: Edge Infrastructure Manager Exporter
type: application
version: 1.22.0
appVersion: "1.21.0"
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
