---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: tenant-config-{{ randAlphaNum 8 | lower }}
  {{- with .Values.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "tenant-config.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tenant-config.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: badouralix/curl-jq@sha256:fe8a5ee49f613495df3b57afa86b39f081bd1b3b9ed61248f46c3d3d7df56092
          command: ["/bin/sh"]
          args:
            - "/configure-tenants.sh"
            - "{{ .Values.params.keycloakUrl }}"
            - "{{ .Values.params.apiUrl }}"
            - "{{.Values.config.defaultOrganization }}"
            - "{{.Values.config.defaultTenant }}"
            - "{{.Values.config.defaultUser }}"
          env:
            - name: ADMIN_USER
              value: "{{ .Values.keycloakAdmin.user }}"
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.keycloakAdmin.passwordSecret.key }}
                  name: {{ .Values.keycloakAdmin.passwordSecret.name }}
            - name: ADMIN_CLIENT
              value: "{{ .Values.keycloakAdmin.client }}"
          volumeMounts:
            - mountPath: /configure-tenants.sh
              subPath: configure-tenants.sh
              name: tenant-config
      volumes:
        - name: tenant-config
          configMap:
            name: {{ include "tenant-config.name" . }}-script
            defaultMode: 0777

