# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- $registry := .Values.global.registry -}}
{{ if .Values.image.registry }}
  {{- $registry = .Values.image.registry -}}
{{ end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-controller.fullname" . }}
  labels:
    {{- include "tenant-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tenant-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tenant-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- if hasKey $registry "name" }}
      {{- with $registry.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "tenant-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if hasKey $registry "name" }}
          image: "{{ $registry.name }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.managerArgs.oamServerAddress }}
          {{- $oamservport:= (splitList ":" .Values.managerArgs.oamServerAddress) | last | atoi }}
          livenessProbe:
            grpc:
              port: {{ $oamservport }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: {{ $oamservport }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          {{- end }}
          args:
            {{- range $key, $value := .Values.managerArgs }}
            - {{ print "-" $key | toYaml -}}={{- $value }}
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - -enableMetrics=true
            {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
          - name: metrics
            containerPort: {{ .Values.metrics.port }}
            protocol: TCP
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VAULT_URL
              value: {{ .Values.vault.url | default "" }}
            - name: VAULT_PKI_ROLE
              value: {{ .Values.vault.role | default "" }}
          volumeMounts:
            - mountPath: /configuration/default/
              name: init-resources
      volumes:
        - name: init-resources
          configMap:
            name: tc-init-resources
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
