# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mps-configmap
data:
  initMPS.sql: |
    -- Contents of initMPS.sql file goes here
    
    \connect orch-infra-mps

    CREATE TABLE IF NOT EXISTS devices(
          guid uuid NOT NULL,
          tags text[],
          hostname varchar(256),
          mpsinstance text, 
          connectionstatus boolean,
          mpsusername text,
          tenantid varchar(36) NOT NULL,
          friendlyname varchar(256),
          dnssuffix varchar(256),
          lastconnected timestamp with time zone,
          lastseen timestamp with time zone,
          lastdisconnected timestamp with time zone,
          deviceinfo JSON,
          CONSTRAINT device_guid UNIQUE(guid),
          PRIMARY KEY (guid, tenantid)
        ); 