# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# NOTICE: This file has been modified by Intel Corporation.
# Original file can be found at https://github.com/tinkerbell/charts.

{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.server.name }}
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
      stack: tinkerbell
      {{- with .Values.server.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name }}
        stack: tinkerbell
        {{- with .Values.server.selector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - args:
            - --backend=kubernetes
            {{- range .Values.server.args }}
            - {{ . }}
            {{- end }}
          image: {{ .Values.server.image.repository }}
          imagePullPolicy: {{ .Values.server.image.imagePullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          name: server
          ports:
            - containerPort: {{ .Values.server.deployment.port }}
              name: {{ .Values.server.deployment.portName }}
            {{- if .Values.server.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.server.healthCheck.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              port: {{ .Values.server.healthCheck.port }}
              path: /healthz
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: {{ .Values.server.healthCheck.port }}
              path: /healthz
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
      serviceAccountName: {{ .Values.server.name }}
{{- end }}
