# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# NOTICE: This file has been modified by Intel Corporation.
# Original file can be found at https://github.com/tinkerbell/charts.

{{- if .Values.server.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
