# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# NOTICE: This file has been modified by Intel Corporation.
# Original file can be found at https://github.com/tinkerbell/charts.

{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.server.name }}
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: {{ .Values.server.service.port }}
    protocol: TCP
    targetPort: {{ .Values.server.deployment.portName }}
    name: {{ .Values.server.deployment.portName }}
  {{- if .Values.server.metrics.enabled }}
  - name: metrics
    port: {{ .Values.server.metrics.port }}
    targetPort: metrics
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Values.server.name }}
{{- end }}
