# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inventory.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    {{- include "inventory.selectorLabels" . | nindent 4 }}
  endpoints:
    - port: metrics
{{ end }}
