# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory.fullname" . }}
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "inventory.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "inventory.fullname" . }}-external
  labels:
    app: {{ template "inventory.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "inventory.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    name: {{ template "inventory.fullname" . }}
    resource: {{ template "inventory.fullname" . }}
    {{- include "inventory.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.external.port }}
      nodePort: {{ .Values.service.external.nodePort }}
      protocol: {{ .Values.service.external.protocol }}
  {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      nodePort: {{ .Values.metrics.external.nodePort }}
      protocol: TCP
      name: metrics
  {{- end }}
{{- end }}
---
{{- if .Values.postgresql.pod.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: inventory-postgresql
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.pod.service.type }}
  ports:
    - port: {{ .Values.postgresql.pod.service.port }}
      targetPort: 5432
      protocol: TCP
      name: sql
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
