# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# NOTICE: This file has been modified by Intel Corporation.
# Original file can be found at https://github.com/tinkerbell/charts.

{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.controller.tinkLeaderElectionRoleBindingName }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.controller.tinkLeaderElectionRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.name }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
