---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: loca-credentials
description: Lenovo Credential Configuration Job
type: application
version: 1.2.0
appVersion: "1.1.0"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
