# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}-external
  labels:
    app: {{ template "api.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.external.port }}
      nodePort: {{ .Values.service.external.nodePort }}
      protocol: {{ .Values.service.external.protocol }}
  {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      nodePort: {{ .Values.metrics.external.nodePort }}
      protocol: TCP
      name: metrics
  {{- end }}
{{- end }}
