---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
{{- $registry := .Values.global.registry -}}
{{ if .Values.image.registry }}
  {{- $registry = .Values.image.registry -}}
{{ end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "attestationstatusmgr-manager.fullname" . }}
  labels:
    {{- include "attestationstatusmgr-manager.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "attestationstatusmgr-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "attestationstatusmgr-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- if hasKey $registry "name" }}
      {{- with $registry.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "attestationstatusmgr-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if hasKey $registry "name" }}
          image: "{{ $registry.name }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.attestationstatusmgr.name }}
              containerPort: {{ .Values.service.attestationstatusmgr.port }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.attestationstatusmgr.oamservaddr }}
           {{- $oamservport:= (splitList ":" .Values.attestationstatusmgr.oamservaddr) | last | atoi }}
          livenessProbe:
            grpc:
              port: {{ $oamservport }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: {{ $oamservport }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          {{- end }}
          args:
          - -serverAddress=0.0.0.0:{{ .Values.service.attestationstatusmgr.port }}
          - -inventoryAddress={{ .Values.inventory.addr }}:{{ .Values.inventory.port }}
          - -oamServerAddress={{ .Values.attestationstatusmgr.oamservaddr }}
          {{- if .Values.attestationstatusmgr.enableTracing }}
          - -enableTracing={{ .Values.attestationstatusmgr.enableTracing }}
          - -traceURL={{ .Values.attestationstatusmgr.traceURL }}
          {{- end }}
          {{- if .Values.globalLogLevel }}
          - -globalLogLevel={{ .Values.globalLogLevel }}
          {{- end}}
          {{- if .Values.metrics.enabled }}
          - -enableMetrics=true
          {{- end }}
          {{- range $key, $value := .Values.serviceArgs }}
          - {{ print "-" $key | toYaml -}}={{- $value }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: OIDC_SERVER_URL
              value: "{{ .Values.oidc.oidc_server_url }}"
            - name: OIDC_TLS_INSECURE_SKIP_VERIFY
              value: "{{ .Values.oidc.oidc_tls_insecure_skip_verify_value }}"
            - name: ALLOW_MISSING_AUTH_CLIENTS
              value: {{ join "," .Values.oidc.clients.bypass | default "" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
