# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }} 
    provisioningServerURL: https://{{ .Values.config.provisioningSvc }}/tink-stack
