# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- $registry := .Values.global.registry -}}
{{ if .Values.image.registry }}
  {{- $registry = .Values.image.registry -}}
{{ end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exporter.fullname" . }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- if hasKey $registry "name" }}
      {{- with $registry.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if hasKey $registry "name" }}
          image: "{{ $registry.name }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range $key, $value := .Values.serviceArgs }}
            - {{ print "-" $key | toYaml -}}={{- $value }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.serviceArgs.oamservaddr }}
          {{- $oamservport:= (splitList ":" .Values.serviceArgs.oamservaddr) | last | atoi }}
          livenessProbe:
            grpc:
              port: {{ $oamservport }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: {{ $oamservport }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: EN_LOKI_URL
              value: "{{ .Values.env.en_loki_url }}" 
            {{- if .Values.humanReadableLogs }}
            - name: HUMAN
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
