# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

{{- if .Values.serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      scheme: HTTP
{{- end}}
